name: IMPREMENTACION DE CI/CD CON GITHUB ACTIONS – DOCKER
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  packages: write # Permiso para escribir en GitHub Container
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # Instalacion de dependencias de python
      - name: Install dependencies
        run: pip install -r requirements.txt
      # Instalacion de dependencias de node
      - name: Install dependencies node
        run: npm install
      # Validacion basica de sintaxis Python
      - name: Check Python syntax
        run: python -m py_compile main.py

      # Login a GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Construccion y push de la imagen Docker a GitHub Container
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/eleaxgaymer138/devops_presta_app:latest
# ghcr.io/cuenta_usuario/nombre_repositorio:tag
